name: Library Build

on:
  push:
    branches:
      - main
      - dev
    paths:
      - Threads.Lib/**
      - Threads.Lib.Tests/**
  pull_request:
    branches: [main]
    paths:
      - Threads.Lib/**
      - Threads.Lib.Tests/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Library
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - run: dotnet fsi build.fsx -- -p ci:library
