name: Sample Build

on:
  push:
    branches:
      - main
      - dev
    paths:
      - Threads.Lib/**
      - Sample/**
  pull_request:
    branches:
      - main
    paths:
      - Threads.Lib/**
      - Sample/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build dotnet 8.0
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - run: dotnet fsi build.fsx -- -p ci:sample
